-- check standard type casts
SELECT
  CASE WHEN
        CAST(NULL AS CHARACTER) IS NULL
    AND CAST(NULL AS NUMERIC) IS NULL
    AND CAST(NULL AS DECIMAL) IS NULL
    AND CAST(NULL AS SMALLINT) IS NULL
    AND CAST(NULL AS INTEGER) IS NULL
    AND CAST(NULL AS INT) IS NULL
    AND CAST(NULL AS BIGINT) IS NULL
    AND CAST(NULL AS FLOAT) IS NULL
    AND CAST(NULL AS REAL) IS NULL
    AND CAST(NULL AS DOUBLE PRECISION) IS NULL
    AND CAST('T' AS BOOLEAN) <> CAST('F' AS BOOLEAN)
  THEN 'T' ELSE 'F' END AS result
